-- ============================================================
--  HABIT TRACKER — Dummy Data
--
--  HOW TO USE:
--  1. Sign up in the app and note your email
--  2. Go to: Supabase Dashboard → Authentication → Users
--  3. Copy your user UUID (e.g. 8d8862b0-7ca7-48c3-a6fe-...)
--  4. In this file: Find & Replace  <<YOUR_USER_ID>>
--     with your actual UUID (keep the single quotes around it)
--  5. Paste the entire file into Supabase SQL Editor → Run
--
--  Inserts: 10 habits, ~594 checks (Jan–Mar 2026),
--           75 mood logs, 11 journal entries, 8 habit notes
-- ============================================================

DO $$
DECLARE
  uid uuid := '<<YOUR_USER_ID>>';

  cat_health uuid; cat_mind uuid; cat_work uuid; cat_body uuid;
  h_wake uuid; h_cold uuid; h_gym uuid; h_meditate uuid; h_read uuid;
  h_nosugar uuid; h_planning uuid; h_code uuid; h_walk uuid; h_sleep uuid;

BEGIN

-- ── Guard: make sure the user exists ──────────────────────
IF NOT EXISTS (SELECT 1 FROM auth.users WHERE id = uid) THEN
  RAISE EXCEPTION 'User % not found. Replace <<YOUR_USER_ID>> with your real UUID.', uid;
END IF;

-- ── Generate UUIDs ────────────────────────────────────────
cat_health := gen_random_uuid(); cat_mind  := gen_random_uuid();
cat_work   := gen_random_uuid(); cat_body  := gen_random_uuid();

h_wake     := gen_random_uuid(); h_cold     := gen_random_uuid();
h_gym      := gen_random_uuid(); h_meditate := gen_random_uuid();
h_read     := gen_random_uuid(); h_nosugar  := gen_random_uuid();
h_planning := gen_random_uuid(); h_code     := gen_random_uuid();
h_walk     := gen_random_uuid(); h_sleep    := gen_random_uuid();

-- ── CATEGORIES ────────────────────────────────────────────
INSERT INTO public.categories (id, user_id, name, color) VALUES
  (cat_health, uid, 'Health', '#3B6D11'),
  (cat_mind,   uid, 'Mind',   '#185FA5'),
  (cat_work,   uid, 'Work',   '#4A3F2F'),
  (cat_body,   uid, 'Body',   '#993556');

-- ── HABITS ────────────────────────────────────────────────
INSERT INTO public.habits
  (id, user_id, category_id, name, emoji, color, freq, custom_days, week_goal, sort_order)
VALUES
  (h_wake,     uid, cat_health, 'Wake up at 06:00', '⏰', '#C4924A', 'daily',    '{}', 6, 1),
  (h_cold,     uid, cat_health, 'Cold Shower',      '🚿', '#185FA5', 'daily',    '{}', 7, 2),
  (h_gym,      uid, cat_body,   'GYM',              '💪', '#4A3F2F', 'weekdays', '{}', 5, 3),
  (h_meditate, uid, cat_mind,   'Meditation',       '🧘', '#3B6D8A', 'daily',    '{}', 6, 4),
  (h_read,     uid, cat_mind,   'Read 10 pages',    '📚', '#3B6D11', 'daily',    '{}', 7, 5),
  (h_nosugar,  uid, cat_health, 'No sugar',         '🚫', '#993556', 'daily',    '{}', 6, 6),
  (h_planning, uid, cat_work,   'Planning',         '📝', '#6D8A3B', 'weekdays', '{}', 5, 7),
  (h_code,     uid, cat_work,   'Code 1 hour',      '💻', '#5B4A8A', 'weekdays', '{}', 5, 8),
  (h_walk,     uid, cat_body,   'Evening walk',     '🌙', '#854F0B', 'daily',    '{}', 5, 9),
  (h_sleep,    uid, cat_health, 'Sleep before 11',  '😴', '#D85A30', 'daily',    '{}', 7, 10);

-- ── HABIT CHECKS ──────────────────────────────────────────
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_wake, uid, '2026-01-01') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_cold, uid, '2026-01-01') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_gym, uid, '2026-01-01') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_meditate, uid, '2026-01-01') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_read, uid, '2026-01-01') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_nosugar, uid, '2026-01-01') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_planning, uid, '2026-01-01') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_code, uid, '2026-01-01') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_walk, uid, '2026-01-01') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_wake, uid, '2026-01-02') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_cold, uid, '2026-01-02') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_read, uid, '2026-01-02') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_nosugar, uid, '2026-01-02') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_planning, uid, '2026-01-02') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_code, uid, '2026-01-02') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_walk, uid, '2026-01-02') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_wake, uid, '2026-01-03') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_cold, uid, '2026-01-03') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_meditate, uid, '2026-01-03') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_nosugar, uid, '2026-01-03') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_walk, uid, '2026-01-03') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_cold, uid, '2026-01-04') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_meditate, uid, '2026-01-04') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_read, uid, '2026-01-04') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_nosugar, uid, '2026-01-04') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_walk, uid, '2026-01-04') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_sleep, uid, '2026-01-04') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_wake, uid, '2026-01-05') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_cold, uid, '2026-01-05') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_gym, uid, '2026-01-05') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_meditate, uid, '2026-01-05') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_read, uid, '2026-01-05') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_nosugar, uid, '2026-01-05') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_planning, uid, '2026-01-05') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_walk, uid, '2026-01-05') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_sleep, uid, '2026-01-05') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_wake, uid, '2026-01-06') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_cold, uid, '2026-01-06') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_gym, uid, '2026-01-06') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_meditate, uid, '2026-01-06') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_read, uid, '2026-01-06') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_nosugar, uid, '2026-01-06') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_planning, uid, '2026-01-06') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_code, uid, '2026-01-06') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_walk, uid, '2026-01-06') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_sleep, uid, '2026-01-06') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_wake, uid, '2026-01-07') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_cold, uid, '2026-01-07') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_gym, uid, '2026-01-07') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_meditate, uid, '2026-01-07') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_read, uid, '2026-01-07') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_nosugar, uid, '2026-01-07') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_planning, uid, '2026-01-07') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_code, uid, '2026-01-07') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_walk, uid, '2026-01-07') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_sleep, uid, '2026-01-07') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_wake, uid, '2026-01-08') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_cold, uid, '2026-01-08') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_gym, uid, '2026-01-08') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_read, uid, '2026-01-08') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_nosugar, uid, '2026-01-08') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_planning, uid, '2026-01-08') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_code, uid, '2026-01-08') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_walk, uid, '2026-01-08') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_sleep, uid, '2026-01-08') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_wake, uid, '2026-01-09') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_cold, uid, '2026-01-09') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_gym, uid, '2026-01-09') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_meditate, uid, '2026-01-09') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_read, uid, '2026-01-09') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_planning, uid, '2026-01-09') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_code, uid, '2026-01-09') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_walk, uid, '2026-01-09') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_sleep, uid, '2026-01-09') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_wake, uid, '2026-01-10') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_cold, uid, '2026-01-10') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_meditate, uid, '2026-01-10') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_read, uid, '2026-01-10') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_wake, uid, '2026-01-11') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_cold, uid, '2026-01-11') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_meditate, uid, '2026-01-11') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_nosugar, uid, '2026-01-11') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_walk, uid, '2026-01-11') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_sleep, uid, '2026-01-11') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_wake, uid, '2026-01-12') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_cold, uid, '2026-01-12') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_meditate, uid, '2026-01-12') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_read, uid, '2026-01-12') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_nosugar, uid, '2026-01-12') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_planning, uid, '2026-01-12') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_code, uid, '2026-01-12') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_walk, uid, '2026-01-12') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_sleep, uid, '2026-01-12') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_wake, uid, '2026-01-13') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_cold, uid, '2026-01-13') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_gym, uid, '2026-01-13') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_meditate, uid, '2026-01-13') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_read, uid, '2026-01-13') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_nosugar, uid, '2026-01-13') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_planning, uid, '2026-01-13') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_code, uid, '2026-01-13') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_walk, uid, '2026-01-13') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_sleep, uid, '2026-01-13') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_wake, uid, '2026-01-14') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_cold, uid, '2026-01-14') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_gym, uid, '2026-01-14') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_meditate, uid, '2026-01-14') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_read, uid, '2026-01-14') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_nosugar, uid, '2026-01-14') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_code, uid, '2026-01-14') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_sleep, uid, '2026-01-14') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_wake, uid, '2026-01-15') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_cold, uid, '2026-01-15') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_gym, uid, '2026-01-15') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_read, uid, '2026-01-15') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_nosugar, uid, '2026-01-15') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_planning, uid, '2026-01-15') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_code, uid, '2026-01-15') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_sleep, uid, '2026-01-15') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_wake, uid, '2026-01-16') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_cold, uid, '2026-01-16') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_gym, uid, '2026-01-16') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_meditate, uid, '2026-01-16') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_read, uid, '2026-01-16') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_nosugar, uid, '2026-01-16') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_planning, uid, '2026-01-16') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_code, uid, '2026-01-16') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_walk, uid, '2026-01-16') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_sleep, uid, '2026-01-16') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_cold, uid, '2026-01-17') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_meditate, uid, '2026-01-17') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_read, uid, '2026-01-17') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_nosugar, uid, '2026-01-17') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_walk, uid, '2026-01-17') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_cold, uid, '2026-01-18') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_meditate, uid, '2026-01-18') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_read, uid, '2026-01-18') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_sleep, uid, '2026-01-18') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_wake, uid, '2026-01-19') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_cold, uid, '2026-01-19') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_gym, uid, '2026-01-19') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_read, uid, '2026-01-19') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_nosugar, uid, '2026-01-19') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_planning, uid, '2026-01-19') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_code, uid, '2026-01-19') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_walk, uid, '2026-01-19') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_sleep, uid, '2026-01-19') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_wake, uid, '2026-01-20') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_cold, uid, '2026-01-20') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_gym, uid, '2026-01-20') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_meditate, uid, '2026-01-20') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_read, uid, '2026-01-20') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_nosugar, uid, '2026-01-20') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_planning, uid, '2026-01-20') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_code, uid, '2026-01-20') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_walk, uid, '2026-01-20') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_sleep, uid, '2026-01-20') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_wake, uid, '2026-01-21') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_cold, uid, '2026-01-21') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_gym, uid, '2026-01-21') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_meditate, uid, '2026-01-21') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_read, uid, '2026-01-21') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_nosugar, uid, '2026-01-21') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_planning, uid, '2026-01-21') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_code, uid, '2026-01-21') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_walk, uid, '2026-01-21') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_sleep, uid, '2026-01-21') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_wake, uid, '2026-01-22') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_cold, uid, '2026-01-22') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_gym, uid, '2026-01-22') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_meditate, uid, '2026-01-22') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_read, uid, '2026-01-22') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_planning, uid, '2026-01-22') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_code, uid, '2026-01-22') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_walk, uid, '2026-01-22') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_sleep, uid, '2026-01-22') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_wake, uid, '2026-01-23') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_cold, uid, '2026-01-23') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_gym, uid, '2026-01-23') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_meditate, uid, '2026-01-23') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_read, uid, '2026-01-23') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_planning, uid, '2026-01-23') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_code, uid, '2026-01-23') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_walk, uid, '2026-01-23') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_sleep, uid, '2026-01-23') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_wake, uid, '2026-01-24') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_cold, uid, '2026-01-24') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_meditate, uid, '2026-01-24') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_read, uid, '2026-01-24') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_nosugar, uid, '2026-01-24') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_walk, uid, '2026-01-24') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_cold, uid, '2026-01-25') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_meditate, uid, '2026-01-25') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_read, uid, '2026-01-25') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_nosugar, uid, '2026-01-25') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_sleep, uid, '2026-01-25') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_wake, uid, '2026-01-26') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_cold, uid, '2026-01-26') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_gym, uid, '2026-01-26') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_meditate, uid, '2026-01-26') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_read, uid, '2026-01-26') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_nosugar, uid, '2026-01-26') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_planning, uid, '2026-01-26') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_code, uid, '2026-01-26') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_walk, uid, '2026-01-26') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_sleep, uid, '2026-01-26') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_wake, uid, '2026-01-27') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_cold, uid, '2026-01-27') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_gym, uid, '2026-01-27') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_meditate, uid, '2026-01-27') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_read, uid, '2026-01-27') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_nosugar, uid, '2026-01-27') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_planning, uid, '2026-01-27') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_code, uid, '2026-01-27') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_walk, uid, '2026-01-27') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_sleep, uid, '2026-01-27') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_wake, uid, '2026-01-28') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_cold, uid, '2026-01-28') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_gym, uid, '2026-01-28') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_meditate, uid, '2026-01-28') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_read, uid, '2026-01-28') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_nosugar, uid, '2026-01-28') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_code, uid, '2026-01-28') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_walk, uid, '2026-01-28') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_sleep, uid, '2026-01-28') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_wake, uid, '2026-01-29') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_cold, uid, '2026-01-29') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_gym, uid, '2026-01-29') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_meditate, uid, '2026-01-29') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_read, uid, '2026-01-29') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_nosugar, uid, '2026-01-29') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_planning, uid, '2026-01-29') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_code, uid, '2026-01-29') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_walk, uid, '2026-01-29') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_sleep, uid, '2026-01-29') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_wake, uid, '2026-01-30') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_cold, uid, '2026-01-30') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_gym, uid, '2026-01-30') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_read, uid, '2026-01-30') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_nosugar, uid, '2026-01-30') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_planning, uid, '2026-01-30') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_code, uid, '2026-01-30') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_cold, uid, '2026-01-31') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_read, uid, '2026-01-31') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_nosugar, uid, '2026-01-31') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_sleep, uid, '2026-01-31') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_cold, uid, '2026-02-01') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_meditate, uid, '2026-02-01') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_read, uid, '2026-02-01') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_walk, uid, '2026-02-01') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_cold, uid, '2026-02-02') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_gym, uid, '2026-02-02') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_meditate, uid, '2026-02-02') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_read, uid, '2026-02-02') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_nosugar, uid, '2026-02-02') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_planning, uid, '2026-02-02') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_sleep, uid, '2026-02-02') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_wake, uid, '2026-02-03') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_cold, uid, '2026-02-03') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_gym, uid, '2026-02-03') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_meditate, uid, '2026-02-03') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_read, uid, '2026-02-03') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_nosugar, uid, '2026-02-03') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_planning, uid, '2026-02-03') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_code, uid, '2026-02-03') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_walk, uid, '2026-02-03') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_sleep, uid, '2026-02-03') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_wake, uid, '2026-02-04') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_cold, uid, '2026-02-04') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_gym, uid, '2026-02-04') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_read, uid, '2026-02-04') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_nosugar, uid, '2026-02-04') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_planning, uid, '2026-02-04') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_code, uid, '2026-02-04') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_walk, uid, '2026-02-04') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_sleep, uid, '2026-02-04') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_wake, uid, '2026-02-05') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_cold, uid, '2026-02-05') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_gym, uid, '2026-02-05') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_meditate, uid, '2026-02-05') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_nosugar, uid, '2026-02-05') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_planning, uid, '2026-02-05') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_code, uid, '2026-02-05') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_walk, uid, '2026-02-05') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_sleep, uid, '2026-02-05') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_wake, uid, '2026-02-06') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_cold, uid, '2026-02-06') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_gym, uid, '2026-02-06') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_read, uid, '2026-02-06') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_nosugar, uid, '2026-02-06') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_planning, uid, '2026-02-06') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_code, uid, '2026-02-06') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_walk, uid, '2026-02-06') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_sleep, uid, '2026-02-06') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_wake, uid, '2026-02-07') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_cold, uid, '2026-02-07') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_walk, uid, '2026-02-07') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_sleep, uid, '2026-02-07') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_cold, uid, '2026-02-08') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_meditate, uid, '2026-02-08') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_read, uid, '2026-02-08') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_nosugar, uid, '2026-02-08') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_walk, uid, '2026-02-08') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_wake, uid, '2026-02-09') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_cold, uid, '2026-02-09') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_gym, uid, '2026-02-09') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_meditate, uid, '2026-02-09') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_read, uid, '2026-02-09') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_nosugar, uid, '2026-02-09') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_planning, uid, '2026-02-09') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_code, uid, '2026-02-09') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_walk, uid, '2026-02-09') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_sleep, uid, '2026-02-09') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_wake, uid, '2026-02-10') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_cold, uid, '2026-02-10') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_gym, uid, '2026-02-10') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_meditate, uid, '2026-02-10') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_nosugar, uid, '2026-02-10') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_planning, uid, '2026-02-10') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_code, uid, '2026-02-10') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_walk, uid, '2026-02-10') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_sleep, uid, '2026-02-10') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_wake, uid, '2026-02-11') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_cold, uid, '2026-02-11') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_gym, uid, '2026-02-11') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_meditate, uid, '2026-02-11') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_read, uid, '2026-02-11') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_nosugar, uid, '2026-02-11') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_planning, uid, '2026-02-11') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_code, uid, '2026-02-11') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_walk, uid, '2026-02-11') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_sleep, uid, '2026-02-11') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_wake, uid, '2026-02-12') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_cold, uid, '2026-02-12') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_gym, uid, '2026-02-12') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_meditate, uid, '2026-02-12') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_read, uid, '2026-02-12') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_nosugar, uid, '2026-02-12') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_planning, uid, '2026-02-12') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_code, uid, '2026-02-12') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_walk, uid, '2026-02-12') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_sleep, uid, '2026-02-12') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_cold, uid, '2026-02-13') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_gym, uid, '2026-02-13') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_meditate, uid, '2026-02-13') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_read, uid, '2026-02-13') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_nosugar, uid, '2026-02-13') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_planning, uid, '2026-02-13') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_code, uid, '2026-02-13') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_walk, uid, '2026-02-13') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_sleep, uid, '2026-02-13') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_wake, uid, '2026-02-14') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_cold, uid, '2026-02-14') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_read, uid, '2026-02-14') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_nosugar, uid, '2026-02-14') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_walk, uid, '2026-02-14') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_sleep, uid, '2026-02-14') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_wake, uid, '2026-02-15') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_cold, uid, '2026-02-15') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_meditate, uid, '2026-02-15') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_read, uid, '2026-02-15') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_walk, uid, '2026-02-15') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_sleep, uid, '2026-02-15') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_wake, uid, '2026-02-16') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_cold, uid, '2026-02-16') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_gym, uid, '2026-02-16') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_meditate, uid, '2026-02-16') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_read, uid, '2026-02-16') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_nosugar, uid, '2026-02-16') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_planning, uid, '2026-02-16') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_code, uid, '2026-02-16') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_walk, uid, '2026-02-16') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_wake, uid, '2026-02-17') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_cold, uid, '2026-02-17') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_gym, uid, '2026-02-17') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_meditate, uid, '2026-02-17') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_read, uid, '2026-02-17') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_nosugar, uid, '2026-02-17') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_planning, uid, '2026-02-17') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_walk, uid, '2026-02-17') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_sleep, uid, '2026-02-17') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_wake, uid, '2026-02-18') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_cold, uid, '2026-02-18') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_gym, uid, '2026-02-18') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_meditate, uid, '2026-02-18') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_read, uid, '2026-02-18') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_nosugar, uid, '2026-02-18') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_planning, uid, '2026-02-18') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_code, uid, '2026-02-18') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_walk, uid, '2026-02-18') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_sleep, uid, '2026-02-18') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_wake, uid, '2026-02-19') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_cold, uid, '2026-02-19') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_gym, uid, '2026-02-19') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_meditate, uid, '2026-02-19') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_read, uid, '2026-02-19') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_nosugar, uid, '2026-02-19') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_planning, uid, '2026-02-19') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_code, uid, '2026-02-19') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_walk, uid, '2026-02-19') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_sleep, uid, '2026-02-19') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_wake, uid, '2026-02-20') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_cold, uid, '2026-02-20') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_meditate, uid, '2026-02-20') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_read, uid, '2026-02-20') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_nosugar, uid, '2026-02-20') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_planning, uid, '2026-02-20') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_walk, uid, '2026-02-20') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_sleep, uid, '2026-02-20') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_wake, uid, '2026-02-21') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_meditate, uid, '2026-02-21') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_read, uid, '2026-02-21') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_nosugar, uid, '2026-02-21') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_wake, uid, '2026-02-22') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_cold, uid, '2026-02-22') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_meditate, uid, '2026-02-22') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_read, uid, '2026-02-22') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_nosugar, uid, '2026-02-22') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_walk, uid, '2026-02-22') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_wake, uid, '2026-02-23') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_cold, uid, '2026-02-23') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_gym, uid, '2026-02-23') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_meditate, uid, '2026-02-23') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_read, uid, '2026-02-23') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_nosugar, uid, '2026-02-23') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_planning, uid, '2026-02-23') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_code, uid, '2026-02-23') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_walk, uid, '2026-02-23') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_sleep, uid, '2026-02-23') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_wake, uid, '2026-02-24') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_cold, uid, '2026-02-24') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_gym, uid, '2026-02-24') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_meditate, uid, '2026-02-24') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_read, uid, '2026-02-24') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_nosugar, uid, '2026-02-24') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_planning, uid, '2026-02-24') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_code, uid, '2026-02-24') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_walk, uid, '2026-02-24') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_wake, uid, '2026-02-25') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_cold, uid, '2026-02-25') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_meditate, uid, '2026-02-25') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_read, uid, '2026-02-25') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_nosugar, uid, '2026-02-25') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_code, uid, '2026-02-25') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_walk, uid, '2026-02-25') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_sleep, uid, '2026-02-25') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_wake, uid, '2026-02-26') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_cold, uid, '2026-02-26') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_gym, uid, '2026-02-26') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_meditate, uid, '2026-02-26') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_read, uid, '2026-02-26') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_nosugar, uid, '2026-02-26') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_code, uid, '2026-02-26') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_walk, uid, '2026-02-26') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_sleep, uid, '2026-02-26') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_wake, uid, '2026-02-27') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_cold, uid, '2026-02-27') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_gym, uid, '2026-02-27') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_meditate, uid, '2026-02-27') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_read, uid, '2026-02-27') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_code, uid, '2026-02-27') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_sleep, uid, '2026-02-27') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_wake, uid, '2026-02-28') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_cold, uid, '2026-02-28') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_meditate, uid, '2026-02-28') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_read, uid, '2026-02-28') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_walk, uid, '2026-02-28') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_sleep, uid, '2026-02-28') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_cold, uid, '2026-03-01') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_meditate, uid, '2026-03-01') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_walk, uid, '2026-03-01') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_sleep, uid, '2026-03-01') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_wake, uid, '2026-03-02') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_cold, uid, '2026-03-02') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_gym, uid, '2026-03-02') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_read, uid, '2026-03-02') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_nosugar, uid, '2026-03-02') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_planning, uid, '2026-03-02') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_code, uid, '2026-03-02') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_walk, uid, '2026-03-02') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_sleep, uid, '2026-03-02') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_wake, uid, '2026-03-03') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_cold, uid, '2026-03-03') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_gym, uid, '2026-03-03') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_meditate, uid, '2026-03-03') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_read, uid, '2026-03-03') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_nosugar, uid, '2026-03-03') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_planning, uid, '2026-03-03') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_code, uid, '2026-03-03') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_walk, uid, '2026-03-03') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_sleep, uid, '2026-03-03') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_wake, uid, '2026-03-04') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_cold, uid, '2026-03-04') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_gym, uid, '2026-03-04') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_meditate, uid, '2026-03-04') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_read, uid, '2026-03-04') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_nosugar, uid, '2026-03-04') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_planning, uid, '2026-03-04') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_code, uid, '2026-03-04') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_walk, uid, '2026-03-04') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_sleep, uid, '2026-03-04') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_wake, uid, '2026-03-05') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_cold, uid, '2026-03-05') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_gym, uid, '2026-03-05') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_meditate, uid, '2026-03-05') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_read, uid, '2026-03-05') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_nosugar, uid, '2026-03-05') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_planning, uid, '2026-03-05') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_code, uid, '2026-03-05') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_walk, uid, '2026-03-05') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_sleep, uid, '2026-03-05') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_wake, uid, '2026-03-06') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_cold, uid, '2026-03-06') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_gym, uid, '2026-03-06') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_read, uid, '2026-03-06') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_planning, uid, '2026-03-06') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_code, uid, '2026-03-06') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_walk, uid, '2026-03-06') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_sleep, uid, '2026-03-06') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_wake, uid, '2026-03-07') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_cold, uid, '2026-03-07') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_read, uid, '2026-03-07') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_walk, uid, '2026-03-07') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_sleep, uid, '2026-03-07') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_wake, uid, '2026-03-08') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_cold, uid, '2026-03-08') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_meditate, uid, '2026-03-08') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_read, uid, '2026-03-08') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_nosugar, uid, '2026-03-08') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_wake, uid, '2026-03-09') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_cold, uid, '2026-03-09') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_gym, uid, '2026-03-09') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_meditate, uid, '2026-03-09') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_read, uid, '2026-03-09') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_nosugar, uid, '2026-03-09') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_planning, uid, '2026-03-09') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_code, uid, '2026-03-09') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_walk, uid, '2026-03-09') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_sleep, uid, '2026-03-09') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_wake, uid, '2026-03-10') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_cold, uid, '2026-03-10') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_gym, uid, '2026-03-10') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_meditate, uid, '2026-03-10') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_read, uid, '2026-03-10') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_nosugar, uid, '2026-03-10') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_planning, uid, '2026-03-10') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_code, uid, '2026-03-10') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_walk, uid, '2026-03-10') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_sleep, uid, '2026-03-10') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_wake, uid, '2026-03-11') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_cold, uid, '2026-03-11') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_gym, uid, '2026-03-11') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_read, uid, '2026-03-11') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_nosugar, uid, '2026-03-11') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_planning, uid, '2026-03-11') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_walk, uid, '2026-03-11') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_sleep, uid, '2026-03-11') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_wake, uid, '2026-03-12') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_cold, uid, '2026-03-12') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_gym, uid, '2026-03-12') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_meditate, uid, '2026-03-12') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_read, uid, '2026-03-12') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_nosugar, uid, '2026-03-12') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_planning, uid, '2026-03-12') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_code, uid, '2026-03-12') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_walk, uid, '2026-03-12') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_sleep, uid, '2026-03-12') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_wake, uid, '2026-03-13') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_cold, uid, '2026-03-13') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_gym, uid, '2026-03-13') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_meditate, uid, '2026-03-13') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_read, uid, '2026-03-13') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_nosugar, uid, '2026-03-13') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_code, uid, '2026-03-13') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_wake, uid, '2026-03-14') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_cold, uid, '2026-03-14') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_meditate, uid, '2026-03-14') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_nosugar, uid, '2026-03-14') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_walk, uid, '2026-03-14') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_sleep, uid, '2026-03-14') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_cold, uid, '2026-03-15') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_meditate, uid, '2026-03-15') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_read, uid, '2026-03-15') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_nosugar, uid, '2026-03-15') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_walk, uid, '2026-03-15') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_wake, uid, '2026-03-16') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_cold, uid, '2026-03-16') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_gym, uid, '2026-03-16') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_meditate, uid, '2026-03-16') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_read, uid, '2026-03-16') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_nosugar, uid, '2026-03-16') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_planning, uid, '2026-03-16') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_code, uid, '2026-03-16') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_checks (habit_id, user_id, checked_on) VALUES (h_walk, uid, '2026-03-16') ON CONFLICT DO NOTHING;

-- ── MOOD LOGS ──────────────────────────────────────────────
  INSERT INTO public.mood_logs (user_id, log_date, mood, motivation) VALUES (uid, '2026-01-01', 7, 7) ON CONFLICT DO NOTHING;
  INSERT INTO public.mood_logs (user_id, log_date, mood, motivation) VALUES (uid, '2026-01-02', 7, 9) ON CONFLICT DO NOTHING;
  INSERT INTO public.mood_logs (user_id, log_date, mood, motivation) VALUES (uid, '2026-01-03', 7, 6) ON CONFLICT DO NOTHING;
  INSERT INTO public.mood_logs (user_id, log_date, mood, motivation) VALUES (uid, '2026-01-04', 6, 4) ON CONFLICT DO NOTHING;
  INSERT INTO public.mood_logs (user_id, log_date, mood, motivation) VALUES (uid, '2026-01-05', 7, 9) ON CONFLICT DO NOTHING;
  INSERT INTO public.mood_logs (user_id, log_date, mood, motivation) VALUES (uid, '2026-01-06', 8, 8) ON CONFLICT DO NOTHING;
  INSERT INTO public.mood_logs (user_id, log_date, mood, motivation) VALUES (uid, '2026-01-07', 7, 6) ON CONFLICT DO NOTHING;
  INSERT INTO public.mood_logs (user_id, log_date, mood, motivation) VALUES (uid, '2026-01-08', 7, 8) ON CONFLICT DO NOTHING;
  INSERT INTO public.mood_logs (user_id, log_date, mood, motivation) VALUES (uid, '2026-01-09', 6, 8) ON CONFLICT DO NOTHING;
  INSERT INTO public.mood_logs (user_id, log_date, mood, motivation) VALUES (uid, '2026-01-10', 7, 7) ON CONFLICT DO NOTHING;
  INSERT INTO public.mood_logs (user_id, log_date, mood, motivation) VALUES (uid, '2026-01-11', 7, 4) ON CONFLICT DO NOTHING;
  INSERT INTO public.mood_logs (user_id, log_date, mood, motivation) VALUES (uid, '2026-01-12', 8, 8) ON CONFLICT DO NOTHING;
  INSERT INTO public.mood_logs (user_id, log_date, mood, motivation) VALUES (uid, '2026-01-13', 8, 7) ON CONFLICT DO NOTHING;
  INSERT INTO public.mood_logs (user_id, log_date, mood, motivation) VALUES (uid, '2026-01-14', 7, 5) ON CONFLICT DO NOTHING;
  INSERT INTO public.mood_logs (user_id, log_date, mood, motivation) VALUES (uid, '2026-01-15', 8, 6) ON CONFLICT DO NOTHING;
  INSERT INTO public.mood_logs (user_id, log_date, mood, motivation) VALUES (uid, '2026-01-16', 6, 7) ON CONFLICT DO NOTHING;
  INSERT INTO public.mood_logs (user_id, log_date, mood, motivation) VALUES (uid, '2026-01-17', 5, 6) ON CONFLICT DO NOTHING;
  INSERT INTO public.mood_logs (user_id, log_date, mood, motivation) VALUES (uid, '2026-01-18', 7, 6) ON CONFLICT DO NOTHING;
  INSERT INTO public.mood_logs (user_id, log_date, mood, motivation) VALUES (uid, '2026-01-19', 9, 9) ON CONFLICT DO NOTHING;
  INSERT INTO public.mood_logs (user_id, log_date, mood, motivation) VALUES (uid, '2026-01-20', 7, 7) ON CONFLICT DO NOTHING;
  INSERT INTO public.mood_logs (user_id, log_date, mood, motivation) VALUES (uid, '2026-01-21', 6, 7) ON CONFLICT DO NOTHING;
  INSERT INTO public.mood_logs (user_id, log_date, mood, motivation) VALUES (uid, '2026-01-22', 8, 8) ON CONFLICT DO NOTHING;
  INSERT INTO public.mood_logs (user_id, log_date, mood, motivation) VALUES (uid, '2026-01-23', 7, 8) ON CONFLICT DO NOTHING;
  INSERT INTO public.mood_logs (user_id, log_date, mood, motivation) VALUES (uid, '2026-01-24', 7, 7) ON CONFLICT DO NOTHING;
  INSERT INTO public.mood_logs (user_id, log_date, mood, motivation) VALUES (uid, '2026-01-25', 6, 5) ON CONFLICT DO NOTHING;
  INSERT INTO public.mood_logs (user_id, log_date, mood, motivation) VALUES (uid, '2026-01-26', 7, 10) ON CONFLICT DO NOTHING;
  INSERT INTO public.mood_logs (user_id, log_date, mood, motivation) VALUES (uid, '2026-01-27', 6, 8) ON CONFLICT DO NOTHING;
  INSERT INTO public.mood_logs (user_id, log_date, mood, motivation) VALUES (uid, '2026-01-28', 7, 6) ON CONFLICT DO NOTHING;
  INSERT INTO public.mood_logs (user_id, log_date, mood, motivation) VALUES (uid, '2026-01-29', 9, 7) ON CONFLICT DO NOTHING;
  INSERT INTO public.mood_logs (user_id, log_date, mood, motivation) VALUES (uid, '2026-01-30', 6, 7) ON CONFLICT DO NOTHING;
  INSERT INTO public.mood_logs (user_id, log_date, mood, motivation) VALUES (uid, '2026-01-31', 5, 7) ON CONFLICT DO NOTHING;
  INSERT INTO public.mood_logs (user_id, log_date, mood, motivation) VALUES (uid, '2026-02-01', 7, 6) ON CONFLICT DO NOTHING;
  INSERT INTO public.mood_logs (user_id, log_date, mood, motivation) VALUES (uid, '2026-02-02', 7, 10) ON CONFLICT DO NOTHING;
  INSERT INTO public.mood_logs (user_id, log_date, mood, motivation) VALUES (uid, '2026-02-03', 7, 9) ON CONFLICT DO NOTHING;
  INSERT INTO public.mood_logs (user_id, log_date, mood, motivation) VALUES (uid, '2026-02-04', 5, 5) ON CONFLICT DO NOTHING;
  INSERT INTO public.mood_logs (user_id, log_date, mood, motivation) VALUES (uid, '2026-02-05', 8, 8) ON CONFLICT DO NOTHING;
  INSERT INTO public.mood_logs (user_id, log_date, mood, motivation) VALUES (uid, '2026-02-06', 8, 8) ON CONFLICT DO NOTHING;
  INSERT INTO public.mood_logs (user_id, log_date, mood, motivation) VALUES (uid, '2026-02-07', 6, 5) ON CONFLICT DO NOTHING;
  INSERT INTO public.mood_logs (user_id, log_date, mood, motivation) VALUES (uid, '2026-02-08', 7, 5) ON CONFLICT DO NOTHING;
  INSERT INTO public.mood_logs (user_id, log_date, mood, motivation) VALUES (uid, '2026-02-09', 9, 9) ON CONFLICT DO NOTHING;
  INSERT INTO public.mood_logs (user_id, log_date, mood, motivation) VALUES (uid, '2026-02-10', 6, 8) ON CONFLICT DO NOTHING;
  INSERT INTO public.mood_logs (user_id, log_date, mood, motivation) VALUES (uid, '2026-02-11', 6, 6) ON CONFLICT DO NOTHING;
  INSERT INTO public.mood_logs (user_id, log_date, mood, motivation) VALUES (uid, '2026-02-12', 8, 7) ON CONFLICT DO NOTHING;
  INSERT INTO public.mood_logs (user_id, log_date, mood, motivation) VALUES (uid, '2026-02-13', 8, 7) ON CONFLICT DO NOTHING;
  INSERT INTO public.mood_logs (user_id, log_date, mood, motivation) VALUES (uid, '2026-02-14', 5, 6) ON CONFLICT DO NOTHING;
  INSERT INTO public.mood_logs (user_id, log_date, mood, motivation) VALUES (uid, '2026-02-15', 6, 6) ON CONFLICT DO NOTHING;
  INSERT INTO public.mood_logs (user_id, log_date, mood, motivation) VALUES (uid, '2026-02-16', 8, 9) ON CONFLICT DO NOTHING;
  INSERT INTO public.mood_logs (user_id, log_date, mood, motivation) VALUES (uid, '2026-02-17', 8, 8) ON CONFLICT DO NOTHING;
  INSERT INTO public.mood_logs (user_id, log_date, mood, motivation) VALUES (uid, '2026-02-18', 7, 5) ON CONFLICT DO NOTHING;
  INSERT INTO public.mood_logs (user_id, log_date, mood, motivation) VALUES (uid, '2026-02-19', 8, 6) ON CONFLICT DO NOTHING;
  INSERT INTO public.mood_logs (user_id, log_date, mood, motivation) VALUES (uid, '2026-02-20', 7, 8) ON CONFLICT DO NOTHING;
  INSERT INTO public.mood_logs (user_id, log_date, mood, motivation) VALUES (uid, '2026-02-21', 6, 5) ON CONFLICT DO NOTHING;
  INSERT INTO public.mood_logs (user_id, log_date, mood, motivation) VALUES (uid, '2026-02-22', 6, 6) ON CONFLICT DO NOTHING;
  INSERT INTO public.mood_logs (user_id, log_date, mood, motivation) VALUES (uid, '2026-02-23', 7, 10) ON CONFLICT DO NOTHING;
  INSERT INTO public.mood_logs (user_id, log_date, mood, motivation) VALUES (uid, '2026-02-24', 8, 8) ON CONFLICT DO NOTHING;
  INSERT INTO public.mood_logs (user_id, log_date, mood, motivation) VALUES (uid, '2026-02-25', 6, 5) ON CONFLICT DO NOTHING;
  INSERT INTO public.mood_logs (user_id, log_date, mood, motivation) VALUES (uid, '2026-02-26', 7, 8) ON CONFLICT DO NOTHING;
  INSERT INTO public.mood_logs (user_id, log_date, mood, motivation) VALUES (uid, '2026-02-27', 7, 9) ON CONFLICT DO NOTHING;
  INSERT INTO public.mood_logs (user_id, log_date, mood, motivation) VALUES (uid, '2026-02-28', 6, 7) ON CONFLICT DO NOTHING;
  INSERT INTO public.mood_logs (user_id, log_date, mood, motivation) VALUES (uid, '2026-03-01', 6, 4) ON CONFLICT DO NOTHING;
  INSERT INTO public.mood_logs (user_id, log_date, mood, motivation) VALUES (uid, '2026-03-02', 7, 9) ON CONFLICT DO NOTHING;
  INSERT INTO public.mood_logs (user_id, log_date, mood, motivation) VALUES (uid, '2026-03-03', 8, 7) ON CONFLICT DO NOTHING;
  INSERT INTO public.mood_logs (user_id, log_date, mood, motivation) VALUES (uid, '2026-03-04', 6, 6) ON CONFLICT DO NOTHING;
  INSERT INTO public.mood_logs (user_id, log_date, mood, motivation) VALUES (uid, '2026-03-05', 9, 7) ON CONFLICT DO NOTHING;
  INSERT INTO public.mood_logs (user_id, log_date, mood, motivation) VALUES (uid, '2026-03-06', 6, 7) ON CONFLICT DO NOTHING;
  INSERT INTO public.mood_logs (user_id, log_date, mood, motivation) VALUES (uid, '2026-03-07', 7, 7) ON CONFLICT DO NOTHING;
  INSERT INTO public.mood_logs (user_id, log_date, mood, motivation) VALUES (uid, '2026-03-08', 5, 6) ON CONFLICT DO NOTHING;
  INSERT INTO public.mood_logs (user_id, log_date, mood, motivation) VALUES (uid, '2026-03-09', 7, 9) ON CONFLICT DO NOTHING;
  INSERT INTO public.mood_logs (user_id, log_date, mood, motivation) VALUES (uid, '2026-03-10', 8, 7) ON CONFLICT DO NOTHING;
  INSERT INTO public.mood_logs (user_id, log_date, mood, motivation) VALUES (uid, '2026-03-11', 7, 6) ON CONFLICT DO NOTHING;
  INSERT INTO public.mood_logs (user_id, log_date, mood, motivation) VALUES (uid, '2026-03-12', 7, 6) ON CONFLICT DO NOTHING;
  INSERT INTO public.mood_logs (user_id, log_date, mood, motivation) VALUES (uid, '2026-03-13', 6, 8) ON CONFLICT DO NOTHING;
  INSERT INTO public.mood_logs (user_id, log_date, mood, motivation) VALUES (uid, '2026-03-14', 5, 7) ON CONFLICT DO NOTHING;
  INSERT INTO public.mood_logs (user_id, log_date, mood, motivation) VALUES (uid, '2026-03-15', 5, 5) ON CONFLICT DO NOTHING;
  INSERT INTO public.mood_logs (user_id, log_date, mood, motivation) VALUES (uid, '2026-03-16', 9, 9) ON CONFLICT DO NOTHING;

-- ── JOURNAL NOTES ──────────────────────────────────────────
  INSERT INTO public.journal_notes (user_id, note_date, content) VALUES (uid, '2026-01-01', 'New year, new system. Not resolutions — habits. Starting with 10 and tracking every single one. The cold shower nearly broke me on day 1. Nearly.') ON CONFLICT DO NOTHING;
  INSERT INTO public.journal_notes (user_id, note_date, content) VALUES (uid, '2026-01-07', 'First full week done. 82% completion. Gym was the hardest — skipped Friday because I told myself I would go Saturday. Did not. Fixing the excuse next week.') ON CONFLICT DO NOTHING;
  INSERT INTO public.journal_notes (user_id, note_date, content) VALUES (uid, '2026-01-14', 'Two weeks in. Cold shower is now automatic. The moment of hesitation before turning the handle is getting shorter. That is the whole game.') ON CONFLICT DO NOTHING;
  INSERT INTO public.journal_notes (user_id, note_date, content) VALUES (uid, '2026-01-21', 'Meditation streak hit 14 days. I do not feel enlightened. I feel slightly less reactive, which is probably the same thing at this stage.') ON CONFLICT DO NOTHING;
  INSERT INTO public.journal_notes (user_id, note_date, content) VALUES (uid, '2026-01-31', 'January closed at 79% overall. Cold shower 96%. No sugar 68% — weekends are the leak. GYM 91% on applicable days. February is about patching the gaps.') ON CONFLICT DO NOTHING;
  INSERT INTO public.journal_notes (user_id, note_date, content) VALUES (uid, '2026-02-03', 'Changed strategy on sugar. Instead of willpower, I stopped buying it. Cannot fail at not eating what is not in the house.') ON CONFLICT DO NOTHING;
  INSERT INTO public.journal_notes (user_id, note_date, content) VALUES (uid, '2026-02-10', 'Reading habit is the most underrated one. 10 pages a day is 300 pages a month, 3600 a year. Compounding applies to knowledge too.') ON CONFLICT DO NOTHING;
  INSERT INTO public.journal_notes (user_id, note_date, content) VALUES (uid, '2026-02-14', 'Missed 3 days of planning this week. The days I do not plan are the days I feel like I am reacting to life instead of directing it.') ON CONFLICT DO NOTHING;
  INSERT INTO public.journal_notes (user_id, note_date, content) VALUES (uid, '2026-02-28', 'February: 81% overall. No sugar improved to 74%. Cold shower still near-perfect. Most improved: planning. Most to fix: sleep consistency.') ON CONFLICT DO NOTHING;
  INSERT INTO public.journal_notes (user_id, note_date, content) VALUES (uid, '2026-03-07', 'Week 1 of March. Building a project while maintaining the habits is a test. Coding streak and habit streak running simultaneously.') ON CONFLICT DO NOTHING;
  INSERT INTO public.journal_notes (user_id, note_date, content) VALUES (uid, '2026-03-14', 'The heatmap is starting to look like something. Two months of consistent green squares makes you want to protect the streak. The visual accountability is real.') ON CONFLICT DO NOTHING;

-- ── HABIT NOTES ────────────────────────────────────────────
  INSERT INTO public.habit_notes (user_id, habit_id, year, month, content) VALUES (uid, h_cold, 2026, 0, 'January was about tolerating it. By week 3 it stopped feeling like punishment and started feeling like a decision. That distinction matters.') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_notes (user_id, habit_id, year, month, content) VALUES (uid, h_gym, 2026, 0, 'Skipped 2 Fridays. The pattern is always the same: told myself I would go Saturday instead. Blocking gym as non-negotiable on calendar next month.') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_notes (user_id, habit_id, year, month, content) VALUES (uid, h_nosugar, 2026, 0, 'Weekends are the weak point. Social situations and tiredness are the two triggers. Awareness is step one.') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_notes (user_id, habit_id, year, month, content) VALUES (uid, h_cold, 2026, 1, 'No longer dreading it. That is the milestone. February is when it became a habit rather than a challenge.') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_notes (user_id, habit_id, year, month, content) VALUES (uid, h_read, 2026, 1, 'Finished two books this month. 10 pages minimum per day. Some days it was 40. The minimum creates the floor; curiosity creates the ceiling.') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_notes (user_id, habit_id, year, month, content) VALUES (uid, h_sleep, 2026, 1, 'Still the hardest one to close. Strategy for March: phone charges outside the bedroom. Remove the friction source entirely.') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_notes (user_id, habit_id, year, month, content) VALUES (uid, h_code, 2026, 2, 'Building the habit tracker in the coding sessions. The 1-hour minimum is a floor — most sessions ran 2-3 hours once started.') ON CONFLICT DO NOTHING;
  INSERT INTO public.habit_notes (user_id, habit_id, year, month, content) VALUES (uid, h_planning, 2026, 2, 'Evening planning wins. You close the day with intention instead of opening tomorrow in reactive mode.') ON CONFLICT DO NOTHING;

-- ── USER SETTINGS ────────────────────────────────────────
  INSERT INTO public.user_settings (user_id, dark_mode, reminder_on, reminder_time)
  VALUES (uid, false, false, '06:30')
  ON CONFLICT (user_id) DO UPDATE
    SET reminder_time = '06:30';

END $$;
